services:
  # Production API service (serves both API and frontend)
  # Not done yet, might be used
  api:
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped 