services:
  interface:
    build:
      context: ./src/web
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ${WEBDIR}:/app
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ${APIDIR}:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/minflix
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=minflix
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
